import Head from 'next/head'
import Image from 'next/image'
import { getAllFilesMetaData } from '../lib/mdx'
import styles from '../styles/Home.module.css'
import {Link} from 'next/link'


export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">DevUP</a>
        </h1>

        <p className={styles.description}>
          Este Blog esta dedicado a compartir y divulgar temas  desarrollo de aplicaciones web SPA - PWA y E2E Testing {' '}
          
        </p>
        
        <div className={styles.grid}>
          {posts.map(post=>{
          <Link href='/${post.slug}' className={styles.card}>
            <h2>{post.title} &rarr;</h2>
            <p>{post.date}</p>
          </Link>
          })
          }
          
        </div>
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}

export const  getStaticProps = async() => {
  const posts = await getAllFilesMetaData()
  
  return {
  props:{posts}
  }  
}